function [ solved ] = forceSolver( forces, reactions )
%FORCESOLVER is a tool to find reaction forces with known input forces
%   sovled = forceSolver( forces, unknown) reaction forces
%   Forces is [ locX locY locZ Fx Fy Fz Mx My Mz ] 
%   Unkown Forces is same format but the forces and moments correspond to
%   their ability to resist
%   Solved is [ locX locY locZ Fx Fy Fz Mx My Mz ] 

% constants
numReactions = size(reactions, 1);
numForces    = 6; % constant for the number of forces (Fxyz and Mxyz)

% pick a random point to take the moments about
about = rand(3, 1);

% setup the intermediate array that solves the reaction forces
% rows are the sum of forces in x, y, z; then moments in x, y, z
% columns are all the reaction forces (even if they aren't possible)
% last column is the total for that sum
solver = zeros(6, numReactions * numForces + 1);

% ---totals
% summation of forces (x, y, z)
solver(1,end) = -sum(forces(:, 4));
solver(2,end) = -sum(forces(:, 5));
solver(3,end) = -sum(forces(:, 6));

% find the moment generated by the input forces
solver(4,end) = -(dot(forces(:, 2) - about(2), forces(:, 6)) + ...
    dot(forces(:, 3) - about(3), forces(:, 5)) + sum(forces(:, 7)));
solver(5,end) = -(dot(forces(:, 1) - about(1), forces(:, 6)) + ...
    dot(forces(:, 3) - about(3), forces(:, 4)) + sum(forces(:, 8)));
solver(6,end) = -(dot(forces(:, 1) - about(1), forces(:, 5)) + ...
    dot(forces(:, 2) - about(2), forces(:, 4)) + sum(forces(:, 9)));



% ---reaction forces
for i = 1:numReactions
    n = (i-1)*numForces; 
    % input the simple values (forces and moments)
    solver(1, n+1) = reactions(i, 4);
    solver(2, n+2) = reactions(i, 5);
    solver(3, n+3) = reactions(i, 6);
    solver(4, n+4) = reactions(i, 7);
    solver(5, n+5) = reactions(i, 8);
    solver(6, n+6) = reactions(i, 9);
    
    % find the moments generated by the reaction forces
    solver(4, n+3) = (reactions(i, 2) - about(2)) * reactions(i, 6);
    solver(4, n+2) = (reactions(i, 3) - about(3)) * reactions(i, 5);
    solver(5, n+3) = (reactions(i, 1) - about(1)) * reactions(i, 6);
    solver(5, n+1) = (reactions(i, 3) - about(3)) * reactions(i, 4);
    solver(6, n+2) = (reactions(i, 1) - about(1)) * reactions(i, 5);
    solver(6, n+1) = (reactions(i, 2) - about(2)) * reactions(i, 4);
end

% ---solving
% simplify the solver array and try to solve it
zeroForces = all(solver == 0);
removedSolver = solver(:, ~zeroForces);
reducedSolver = rref(removedSolver);

% check if the matrix could solve
unsolveable = 0;
for i = 1:numForces
    if sum(reducedSolver(i, 1:end-1) ~= 0) > 1
        unsolveable = 1;
    end
end

% if the program solved - convert from rref format to output format
solved = zeros(numReactions, 9); % output
k = 1;
if unsolveable ~= 1
    % set the forces
    for i = 1:numReactions
        for n = 1:numForces
            if zeroForces((i-1)*numForces + n) == 0
                solved(i, n + 3) = reducedSolver( k, end);
                k = k + 1;
            end
        end
    end
    % set the locations
    for i = 1:numReactions
        solved(i, 1:3) = reactions(i, 1:3);
    end
    
else
    disp('--The matrix could not be solved')
end