function [ solved ] = forceSolverMulti( forces, reactions )
%FORCESOVLERMULTI Solves "impossible" systems using iteration
%   Detailed explanation goes here

% setting up useful values
numReactions = size(reactions, 1);
numForces    = 6; % constant for the number of forces (Fxyz and Mxyz)
offset       = 3; % number of coordinates (xyz) used to offset matrices

about = rand(1, 3);
target = findTotals(forces, about);
layer = rand(numReactions, numForces)*10.*reactions(:, 4:numForces+offset);

for i = 1:100;
    layer(1, 1) = target(1) - sum(layer(2:end, 1));
    layer(1, 2) = target(2) - sum(layer(2:end, 2));
    layer(1, 3) = target(3) - sum(layer(2:end, 3));
    
    moments = findMoments(layer, reactions, about);
    difference = moments - target(4:6);

    correction(:, 1) = difference(1)./layer(:, 1);
    correction(:, 2) = difference(2)./layer(:, 2);
    correction(:, 3) = difference(3)./layer(:, 3);
    correction(:, 4) = difference(1)./layer(:, 4);
    correction(:, 5) = difference(2)./layer(:, 5);
    correction(:, 6) = difference(3)./layer(:, 6);
    
    correction = correction/10;
    
    layer = layer + correction;
    error = abs(sum(difference)/sum(target))*100;
end
disp(error)
solved = layer;
end

function [totals] = findTotals(forces, about)
%FINDTOTALS Find the totals for the given forces
%   Forces is [ locX locY locZ Fx Fy Fz Mx My Mz ] 
%   about is [ locX locY locZ ] for the point of the moment

totals = zeros(1, 6);

% summation of forces (x, y, z)
totals(1) = -sum(forces(:, 4));
totals(2) = -sum(forces(:, 5));
totals(3) = -sum(forces(:, 6));

% find the moment generated by the input forces
totals(4) = -(dot(forces(:, 2) - about(2), forces(:, 6)) + ...
    dot(forces(:, 3) - about(3), forces(:, 5)) + sum(forces(:, 7)));
totals(5) = -(dot(forces(:, 1) - about(1), forces(:, 6)) + ...
    dot(forces(:, 3) - about(3), forces(:, 4)) + sum(forces(:, 8)));
totals(6) = -(dot(forces(:, 1) - about(1), forces(:, 5)) + ...
    dot(forces(:, 2) - about(2), forces(:, 4)) + sum(forces(:, 9)));
end

function [moments] = findMoments(layer, reactions, about)
moments = zeros(1, 3);
numReactions = size(reactions, 1);

for i = 1:numReactions
    % input the simple values
    moments(1) = layer(i, 1);
    moments(2) = layer(i, 2);
    moments(3) = layer(i, 3);
    
    % find the moments generated by the reaction forces
    moments(1) = (reactions(i, 2) - about(2)) * layer(i, 3);
    moments(1) = (reactions(i, 3) - about(3)) * layer(i, 2);
    moments(2) = (reactions(i, 1) - about(1)) * layer(i, 3);
    moments(2) = (reactions(i, 3) - about(3)) * layer(i, 1);
    moments(3) = (reactions(i, 1) - about(1)) * layer(i, 2);
    moments(3) = (reactions(i, 2) - about(2)) * layer(i, 3);
end
end

